### ISSUE TITLE
Feature request: export other fields in package.json

### ISSUE THREAD

**Issue by dattran1999** [axelpale/genversion#21]
Hi, I'm using this in a project and I'd love to have the option to export other fields in `package.json` (e.g. `name`, `author`, etc.). Let me know if you want that feature as well, then I can raise a PR to add the feature. 

Thank you.

**Comment by axelpale** [comment]
Hi @dattran1999 and thanks for the suggestion. We are planning for the possibility to use a custom template in #19. I will take your suggestion and needs into consideration when designing the template approach. I am hesitant to extend genversion API with explicit, dedicated flags and parameters for `author`, `name` etc because there are so many different properties that it will be an endless road. However, the template approach (#19) might provide a relatively simple way to export those.

Could you briefly describe the **benefit** of exporting `name`, `author` and other fields? In what situations and how it would provide value for the developer or user? Answers to those would help us to make better design decisions when designing the future genversion release. Thank you.

**Comment by bratanon** [comment]
Here is another use case: 
I use commander and what to use the package name, version and description so they always align with each other without manually have to change them.

**Comment by axelpale** [comment]
Today this feature was implemented in release-3.2 branch and will be released in genversion@3.2.0 in near future. A new parameter flag `-P, --property` was added for this and allows selecting one or many properties from package.json, for example `--property name,description,version`

**Comment by axelpale** [comment]
The feature was released today in v3.2.0! See the docs for `--property` flag. 🚀
