### ISSUE TITLE
Question: Why is it bad to import package.json?

### ISSUE THREAD

**Issue by jpwilliams** [axelpale/genversion#5]
The current `README.md` states:

> You could import your package.json into the module but you know it is a naughty thing to do! Genversion to the rescue!

In a few separate projects, I've imported `package.json` to expose version information, but didn't know that it was seen as a bad thing to do.

Why is it bad? As someone stumbling across this library, I'm not sure why I shouldn't be doing it! A quick Google took me to [a StackOverflow question](https://stackoverflow.com/a/10855054) which mentions inadvertently exposing dependency versions when used with [browserify/browserify](https://github.com/browserify/browserify).

Is this the reason? Is it just front-end JavaScript that's at risk here?

Whatever the reasoning, including it in the `README.md` would be a great boon!

**Comment by axelpale** [comment]
Hi and thanks for feedback. You are absolutely right. The discussion you found was the discussion that initially made me build and publish genversion. As a quick fix, I converted "it is a naughty thing" to a link. The link points to the discussion and especially to an answer that describes the problem.

**Comment by jpwilliams** [comment]
Awesome. Thanks so much for that! Beautiful little package that addresses that problem then! I learned something today! 😛

**Comment by abernier** [comment]
The link you point to is precisely the accepted answer to the SO's question "Is there a way to get version from package.json in nodejs code?". That accepted answer recommends using:

```js
var pjson = require('./package.json');
console.log(pjson.version);
```
ie: it recommends importing the `package.json` file and simply read the `version` property

It just adds a limitation **if you use Browserify** to inform you that your `package.json` will become public (which is not necessarily problematic).

NB: if you only do Node.js, this is just fine.

Saying it is a bad thing is clearly **really exaggerated** and a bit opportunistic to promote your package.

**Comment by jpwilliams** [comment]
To argue the point, @abernier, both answers are correct, are they not? The answer in the SO question is a perfectly fine and simple way to get the version string; it's not wrong, but neither is this package for suggesting an alternative.

It's not a firm security requirement that you use something like this, but it _might_ be a good idea if your project demands it. Maybe you're aware that you're using a vulnerable package that you can't update but don't want to publicise that fact?

I'm a bit confused as to why you'd post this pretty aggressive message in an old issue. The `README.md` stating "_it's a naughty thing to do_" is definitely [tongue-in-cheek](https://dictionary.cambridge.org/dictionary/english/tongue-in-cheek) and not some sort of "opportunistic" warning. What's wrong with an optional package that provides some utility over a simpler method?

**Comment by axelpale** [comment]
Hi folks. Thank you @jpwilliams for backing me up here. But also thanks @abernier for the effort of pointing out how some people might react to the wording after learning the topic. However, thumbs downing jp's friendly comment was rather harsh, please blame me if you want to blame somebody instead of focusing to the issue here. Small things matter.

When I published genversion, I thought that only the people who know the dangers of dependency exposure would be the ones to search for the tool and find the tool useful. It seems that after the tool has gained some popularity, also people without this knowledge arrive and wonder if the tool could benefit their project. I understood now that without the knowledge, my relaxed wording in the introducing paragraph might be misleading.

To answer this fortunate situation of increased popularity, I updated the wording to be more informative and for wider audience.

@jpwilliams and @abernier, may I ask how did you stumble upon genversion in the first place? I believe it was not via [the SO page](https://stackoverflow.com/a/10855054/638546). Web search? Npm?
