### ISSUE TITLE
Feature request: checkVersion as CLI command

### ISSUE THREAD

**Issue by caligo-erik** [axelpale/genversion#9]
I'd very much like a CLI function _checkVersion_ that checks the current version file and checks if it is up-to-date.

The function would have the same params as _genversion_ and exit with the following code 
- 0: if the version is as expected (also considering ES6, semicolon etc.) // everything OK
- -1: if the version file is missing
- -2: if the version doesn't match

This would allow for pre-commit-hooks, automated pre-build-checks, CI tests and similar to ensure no package is published/deployed with an outdated or missing version file.

If required, I could have a go at this and make a PR.

I know there is the suggestion with the _postversion.sh_, but I'd rather check the version file before even committing code changes.

**Comment by axelpale** [comment]
Great proposal. I appreciate how you described the purpose and noted that ES6 and other style should also be taken into consideration. Yet there is one detail of that I am not sure. Could you clarify why you chose -1 and -2 for the exit codes? I agree that success code is 0. However, in my experience, the error codes that stop the execution are positive integers, 1 and above (see for example [this bash guide](https://tldp.org/LDP/abs/html/exitcodes.html)). Maybe you known a CLI tool that is designed to return negative codes? I am happy to hear your thoughts on this.

**Comment by caligo-erik** [comment]
> Could you clarify why you chose -1 and -2 for the exit codes?
Sorry, was only an issue of copy/paste between text editor and github page, and didn't remove all the " - ".
So, to rectify my initial proposal: 0 for success, 1 for missing file, 2 for mismatch.

I think it would suffice to refactor the generate function a little: 
create new (internal?) function that creates the content and returns it as string. The existing generate function will call this and write the content to file.

The CLI check function would call the same createContent function and compare it with the content of the file, and exit with the proposed codes.

**Comment by axelpale** [comment]
> 0 for success, 1 for missing file, 2 for mismatch.

Thanks, this sounds good.

> new (internal?) function createContent

True, I see that such refactoring is in order to compare contents.

> I could have a go at this and make a PR.

I would love a PR. It does not need to be perfect and I might restructure it but it is good to have your name in the list of contributors for this nice feature.

**Comment by caligo-erik** [comment]
Hey Axel,
took me some time, but I started working on this issue today.
I've already made a _createContent_ function and re-factored _genVersion_ in a separate branch, but I cannot push: access denied. Do you need to add me as contributor first?

**Comment by axelpale** [comment]
Hi, great! Thank you for your work.

Um, my bad I have not provided contribution instructions. Please fork the repo, make changes to your forked branch (caligo-eric/genversion) and then create a pull request here (axelpale/genversion) for me to approve. This common workflow allows repo owners (me in this case) to verify the code before adopting (merging) it. I usually share pull privileges only with team members I work with on a daily basis. After a successful merge, your name will still become visible in the list of contributors. I hope this helps!

For more details and advanced setup on this Fork & Pull Request workflow see [GitHub Standard Fork & Pull Request Workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962).

**Comment by caligo-erik** [comment]
Sorry, didn't think about forking, first time contributing for me.

You can see the forked code here. 
https://github.com/caligo-erik/genversion/tree/feature/9-chekversionCLI

Would appreciate your input - to see if this is the right direction - before proceeding to implementing tests.

**Comment by axelpale** [comment]
> Sorry, didn't think about forking, first time contributing for me.

No worries, been there myself :)

I read through your commits. It is great to have such concrete development to discuss. Basically things look good. My main concern is if it were better to have a new flag `genversion --check ...` instead of a new command `checkversion`. I think the flag approach has following advantages:

- Some users install genversion globally. The word `genversion` is rare and probably does not collide with any pre-existing programs. I think `checkversion` has higher probability to do so. Therefore a flag is safer.
- To match the API, you had to copy all the code from `bin/genversion.js` to `bin/checkversion.js`. This repetition violates the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). Further API changes would require modification of both files. A new flag would only require a few new lines to `bin/genversion.js` without duplication.

Therefore I think it is better to go with the flag approach. For example `--check` or `--check-version` or `--check-only`. What do you think? I am happy to hear your thoughts.

**Comment by caligo-erik** [comment]
I duplicated the bin/version as quick & dirty solution to try the command line, it was not meant as final solution.
The flag --check-only sounds great.

**Comment by axelpale** [comment]
Okay. Hey, great, `--check-only` it is, let's do that!

**Comment by caligo-erik** [comment]
Sounds great, I'll try to find some time this weekend to implement this

**Comment by caligo-erik** [comment]
I've committed the changes to add the CLI option as discussed.

I also quickly modified existing tests to - after having generated a file, also checks. 
Still fair-weather-testing only, but don't have much time today.

Feedback appreciated.

**Comment by axelpale** [comment]
Hi! Sorry for the delay, it has been a whirlwind over here. I reviewed your code and it looks good. Only tiny thing I spotted was that in `bin/genversion.js` [line 29](https://github.com/axelpale/genversion/compare/master...caligo-erik:feature/9-chekversionCLI#diff-0ceff7fbe8d1ddfb89fbbca6072b08cf1e68e705724c7b9d01943bdb7b273d47R29) there should be a return call `return cv.check(...` instead of plain `cv.check(...`. Otherwise execution might continue beyond the `if (program.checkOnly)` in case cv.check someday becomes truly asynchronous.

Also, as you are new to contributing, feel free to create a pull request from your work early. It does not limit your ability to modify the code further; until a successful merge, pull requests in GitHub automatically keep up with the latest commits in your branch. It is easier for the maintainer (me) to review the code though the lens provided by the PR user interface than navigating in the actual repo.

Not that further commits are strictly needed. I am already very happy of this contribution as-is and happy to merge.

**Comment by caligo-erik** [comment]
I've created a pull request.

**Comment by axelpale** [comment]
I merged yesterday and just a moment ago released genversion v2.3.0 with the new `--check-only` feature. I made some tweaks. Most notably I brought the functionality of `lib/checkVersion.js` into `genversion.check`. The command line usage remains the same but the Node API differs. The latter is mainly because I removed `genversion.checkVersion` in favour of `genversion.check`. See the fresh API docs for details.

I will now close the issue. Thank you!
